### ISSUE TITLE
Question: Why not directly use S3 as the model’s mounted storage, but instead use hostPath mode?

### ISSUE THREAD

**Issue by John-Funcity** [aws-samples/comfyui-on-eks#13]
In the comfyUI comfyui_deployment.yaml, i found that：
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      volumes:
      - name: stable-diffusion-models
        hostPath:
          path: /comfyui-models # Need to sync all models in node's user-data
      - name: comfyui-inputs
        persistentVolumeClaim:
          claimName: comfyui-inputs-pvc # Need to apply sd-inputs-s3.yaml first
      - name: comfyui-outputs
        persistentVolumeClaim:
          claimName: comfyui-outputs-pvc # Need to apply sd-outputs-s3.yaml first
```

the comfyui-outputs and comfyui-inputs use the S3 PVC.
why stable-diffusion-models not do the same ?
